// Code generated by protoc-gen-go. DO NOT EDIT.
// source: defaultcmd.proto

package rpccmdservice

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DefaultRequest struct {
	Reqid                int32    `protobuf:"varint,1,opt,name=reqid,proto3" json:"reqid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultRequest) Reset()         { *m = DefaultRequest{} }
func (m *DefaultRequest) String() string { return proto.CompactTextString(m) }
func (*DefaultRequest) ProtoMessage()    {}
func (*DefaultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f24e0a83d0b1c21, []int{0}
}

func (m *DefaultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultRequest.Unmarshal(m, b)
}
func (m *DefaultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultRequest.Marshal(b, m, deterministic)
}
func (m *DefaultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultRequest.Merge(m, src)
}
func (m *DefaultRequest) XXX_Size() int {
	return xxx_messageInfo_DefaultRequest.Size(m)
}
func (m *DefaultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultRequest proto.InternalMessageInfo

func (m *DefaultRequest) GetReqid() int32 {
	if m != nil {
		return m.Reqid
	}
	return 0
}

type DefaultRequestMsg struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultRequestMsg) Reset()         { *m = DefaultRequestMsg{} }
func (m *DefaultRequestMsg) String() string { return proto.CompactTextString(m) }
func (*DefaultRequestMsg) ProtoMessage()    {}
func (*DefaultRequestMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f24e0a83d0b1c21, []int{1}
}

func (m *DefaultRequestMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultRequestMsg.Unmarshal(m, b)
}
func (m *DefaultRequestMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultRequestMsg.Marshal(b, m, deterministic)
}
func (m *DefaultRequestMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultRequestMsg.Merge(m, src)
}
func (m *DefaultRequestMsg) XXX_Size() int {
	return xxx_messageInfo_DefaultRequestMsg.Size(m)
}
func (m *DefaultRequestMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultRequestMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultRequestMsg proto.InternalMessageInfo

func (m *DefaultRequestMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DefaultResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultResp) Reset()         { *m = DefaultResp{} }
func (m *DefaultResp) String() string { return proto.CompactTextString(m) }
func (*DefaultResp) ProtoMessage()    {}
func (*DefaultResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f24e0a83d0b1c21, []int{2}
}

func (m *DefaultResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultResp.Unmarshal(m, b)
}
func (m *DefaultResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultResp.Marshal(b, m, deterministic)
}
func (m *DefaultResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultResp.Merge(m, src)
}
func (m *DefaultResp) XXX_Size() int {
	return xxx_messageInfo_DefaultResp.Size(m)
}
func (m *DefaultResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultResp.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultResp proto.InternalMessageInfo

func (m *DefaultResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DefaultRequest)(nil), "rpccmdservice.DefaultRequest")
	proto.RegisterType((*DefaultRequestMsg)(nil), "rpccmdservice.DefaultRequestMsg")
	proto.RegisterType((*DefaultResp)(nil), "rpccmdservice.DefaultResp")
}

func init() { proto.RegisterFile("defaultcmd.proto", fileDescriptor_4f24e0a83d0b1c21) }

var fileDescriptor_4f24e0a83d0b1c21 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x49, 0x4d, 0x4b,
	0x2c, 0xcd, 0x29, 0x49, 0xce, 0x4d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x2a,
	0x48, 0x4e, 0xce, 0x4d, 0x29, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x55, 0x52, 0xe3, 0xe2, 0x73,
	0x81, 0x28, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe1, 0x62, 0x2d, 0x4a, 0x2d,
	0xcc, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x70, 0x94, 0x74, 0xb9, 0x04, 0x51,
	0xd5, 0xf9, 0x16, 0xa7, 0x0b, 0x49, 0x70, 0xb1, 0xe7, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7, 0x82,
	0x15, 0x73, 0x06, 0xc1, 0xb8, 0x4a, 0xea, 0x5c, 0xdc, 0x70, 0xe5, 0xc5, 0x05, 0xb8, 0x15, 0x26,
	0xb1, 0x81, 0x5d, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xf4, 0x18, 0x47, 0xa9, 0x00,
	0x00, 0x00,
}
